
server:
  port: 18003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  #开启小写的话必须使用小写
      routes:
        - id: scheduling
          uri: lb://scheduling
          predicates:
            - Path=/scheduling/**
          filters:
            - StripPrefix=1
        - id: taskhandle
          uri: lb://taskhandle
          predicates:
            - Path=/taskhandle/**
          filters:
            - StripPrefix=1
          metadata:
            response-timeout: 3000
            connect-timeout: 2000
    nacos:
      discovery:
        #server-addr: 39.98.249.25:8848
        server-addr: 172.18.130.107:8848